### PR TITLE
refactor: move crypto to llrt_modules

### PR DESCRIPTION
**Pull request by nabetti1720**
### Description of changes

Moving crypto ~~and llrt~~ to llrt_modules. ~~However, the creation of types is just the beginning...~~

### Checklist

- [x] Created unit tests in `tests/unit` and/or in Rust for my feature if needed
- [x] Ran `make fix` to format JS and apply Clippy auto fixes
- [x] Made sure my code didn't add any additional warnings: `make check`
- [x] Added relevant type info in `types/` directory
- [x] Updated documentation if needed ([API.md](API.md)/[README.md](README.md)/Other)

_By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice._

### CODE REVIEW

**Comment by Sytten** [comment]
Could use a different naming than `llrt` even if it is importable by default as `llrt:something`. Same idea that we dont have a module called node. Instead we could use the tag system I proposed to mark the source of those APIs.

**Comment by nabetti1720** [comment]
> Could use a different naming than `llrt` even if it is importable by default as `llrt:something`. Same idea that we dont have a module called node. Instead we could use the tag system I proposed to mark the source of those APIs.

Hi @Sytten , Thank you for your comment.

What other uses exist besides importing with the designation `llrt:something`? Also, for your proposed tag system, if it is already in use somewhere in this project, could you please tell me where?

Sorry, I don't have English and technical skills and would appreciate your time and tips to help me understand your thoughts. :)

**Comment by Sytten** [comment]
I will speak with @richarddavison about it, dont worry about it. I would split the PR to port crypto first since there is not debate around that one and lets postpone the llrt module transfer.

**Comment by nabetti1720** [comment]
> I will speak with @richarddavison about it, dont worry about it. I would split the PR to port crypto first since there is not debate around that one and lets postpone the llrt module transfer.

Thank you for your consideration. There was a place in the crypto module that used llrt:uuid, so I had no choice but to move it at the same time.

**Comment by nabetti1720** [comment]
I wanted to clean up this PR quickly, so I modified the move to llrt_modules to only use the crypto module. It was only a small part of the crypto module's dependency on llrt:uuid, so we decided to use the uuid crate directly.

**Review by richarddavison — APPROVED** [review]
Thanks LGTM

**Pull request merged**
