### PR TITLE
fix: rename xml module to llrt:xml

### PR DESCRIPTION
**Pull request by nabetti1720**
### Issue # (if available)

Related #463 

### Description of changes
The following comment mentions the same issue for the `xml` module.
https://github.com/awslabs/llrt/pull/463#issuecomment-2224111842

In this PR, the same action is taken as was taken in the `hex` module.
In addition, change the prefix from `@llrt/<module>`to `llrt:<module>` to match the current trend of other javascript runtimes.

### Checklist

- [x] Created unit tests in `tests/unit` and/or in Rust for my feature if needed
- [x] Ran `make fix` to format JS and apply Clippy auto fixes
- [x] Made sure my code didn't add any additional warnings: `make check`
- [x] Updated documentation if needed ([API.md](API.md)/[README.md](README.md)/Other)

_By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice._

### CODE REVIEW

**Comment by richarddavison** [comment]
> Did we consider using `llrt:<module>` namespace? I know you started with hex but since it is not released, there is still time to change it. I feel like`@llrt` really is for npm dependencies. Engines are starting to move toward that convention, node is the primary but others like Bun are [starting to do so](https://github.com/oven-sh/bun/blob/110849355cdd640d4d2494a0d0e96375a69c7f72/packages/bun-types/test.d.ts).

Yeah that would be more in-line with what other Runtimes do! @nabetti1720 can you change `@llrt` module prefixes to` llrt:`?

**Comment by nabetti1720** [comment]
> > Did we consider using `llrt:<module>` namespace? I know you started with hex but since it is not released, there is still time to change it. I feel like`@llrt` really is for npm dependencies. Engines are starting to move toward that convention, node is the primary but others like Bun are [starting to do so](https://github.com/oven-sh/bun/blob/110849355cdd640d4d2494a0d0e96375a69c7f72/packages/bun-types/test.d.ts).
> 
> Yeah that would be more in-line with what other Runtimes do! @nabetti1720 can you change `@llrt` module prefixes to` llrt:`?

Of course it is possible. :)

**Comment by Sytten** [comment]
If you want to move them that is less work I have to do. Just make sure they are feature flagged like I started doing :)

**Comment by nabetti1720** [comment]
> If you want to move them that is less work I have to do. Just make sure they are feature flagged like I started doing :)

Thank you for your comment.
I could understand the direction that should be taken. I do not intend to increase your work :) , but let this PR be up to renaming as per your original purpose.

**Review by richarddavison — APPROVED** [review]

**Pull request merged**
