### PR TITLE
Store wakers in Vec instead of busy waiting

### PR DESCRIPTION
**Pull request by richarddavison**
### Description of changes

Store waiters in Vec instead of busy waiting

### Checklist

- [x] Created unit tests in `tests/unit` and/or in Rust for my feature if needed
- [x] Ran `make fix` to format JS and apply Clippy auto fixes
- [x] Made sure my code didn't add any additional warnings: `make check`
- [x] Added relevant type info in `types/` directory
- [x] Updated documentation if needed ([API.md](API.md)/[README.md](README.md)/Other)

_By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice._

### CODE REVIEW

**Comment by Sytten** [comment]
For reference we should look at the watch.
Couple of improvements they made:
- They have a shared struct with one arc, bit faster to create senders/receivers
- It is built on top of the Notify primitive (https://docs.rs/tokio/latest/tokio/sync/struct.Notify.html)
- They use an array of 8 Notify to avoid contention (BigNotify)

See https://docs.rs/tokio/latest/src/tokio/sync/watch.rs.html#1-1477

**Comment by richarddavison** [comment]
> For reference we should look at the watch. Couple of improvements they made:
> 
> * They have a shared struct with one arc, bit faster to create senders/receivers

Ah ofc. Didn't think of that!

> * It is built on top of the Notify primitive (https://docs.rs/tokio/latest/tokio/sync/struct.Notify.html)
> * They use an array of 8 Notify to avoid contention (BigNotify)

That could work but is an internal class, so can't use it

> * For a write heavy load like waker registration a mutex is more performant than a RwLock

Sure, but this isn't very write heavy, right?. The executor won't poll this future again until the waker is called so registration only happens once per copy of mc_oneshot no?

**Comment by Sytten** [comment]
For reference we should look at the watch.
Couple of improvements they made:
- They have a shared struct with one arc, bit faster to create senders/receivers
- It is built on top of the Notify primitive (https://docs.rs/tokio/latest/tokio/sync/struct.Notify.html)
- They use an array of 8 Notify to avoid contention (BigNotify)

See https://docs.rs/tokio/latest/src/tokio/sync/watch.rs.html#1-1477

**Comment by Sytten** [comment]
We can use Notify though if we want.

Mutex is better for mixed workload.

**Pull request merged**
