### PR TITLE
llrt: support windows build

### PR DESCRIPTION
**Pull request by ahaoboy**
### Description of changes
support windows build

### Checklist

- [ ] Created unit tests in `tests/unit` and/or in Rust for my feature if needed
- [ ] Ran `make fix` to format JS and apply Clippy auto fixes
- [ ] Made sure my code didn't add any additional warnings: `make check`
- [ ] Added relevant type info in `types/` directory
- [ ] Updated documentation if needed ([API.md](API.md)/[README.md](README.md)/Other)

### CODE REVIEW

**Review by richarddavison — APPROVED** [review]
Thanks! LGTM!

**Comment by Sytten** [comment]
Lets add CI so it keeps working

**Comment by ahaoboy** [comment]
> Lets add CI so it keeps working

Adding Windows CI may require modifying the make file, which I am not good at :(

**Comment by richarddavison** [comment]
Let's merge for now and we'll add CI for windows later, this state is better than before

**Pull request merged**
