### PR TITLE
ci: upload artifacts on pull_request

### PR DESCRIPTION
**Pull request by ahaoboy**
### Description of changes

upload artifacts on pull_request to compare performance and size changes caused by PR

https://boajs.dev/benchmarks

It is also possible to implement observation diagrams similar to boa

### Checklist

- [ ] Created unit tests in `tests/unit` and/or in Rust for my feature if needed
- [ ] Ran `make fix` to format JS and apply Clippy auto fixes
- [ ] Made sure my code didn't add any additional warnings: `make check`
- [ ] Added relevant type info in `types/` directory
- [ ] Updated documentation if needed ([API.md](API.md)/[README.md](README.md)/Other)

_By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice._

### CODE REVIEW

**Comment by ahaoboy** [comment]
https://github.com/awslabs/llrt/releases/download/v0.3.0-beta/llrt-linux-x64-full-sdk.zip

https://github.com/awslabs/llrt/actions/runs/11850925586

qjs-ng win~

```
 ./llrt ./dist/run.js
Richards: 787
DeltaBlue: 758
Crypto: 902
RayTrace: 1210
EarleyBoyer: 2281
RegExp: 179
Splay: 1618
NavierStokes: 1467
----
Score: 944

./llrt-ng ./dist/run.js
Richards: 797
DeltaBlue: 815
Crypto: 938
RayTrace: 1226
EarleyBoyer: 2255
RegExp: 177
Splay: 1728
NavierStokes: 1551
----
Score: 973
```

**Comment by richarddavison** [comment]
Hi @ahaoboy! We had this before and it's a good suggestion but running the release flow is not the way to do it as it causes significant increase in PR checks. A better way would be to add a "make bench" that runs benchmarks from the `benchmarks` directory
```shell
cargo $(TOOLCHAIN) run -r --target $(CURRENT_TARGET) -- benchmark/v8-v7
cargo $(TOOLCHAIN) run -r --target $(CURRENT_TARGET) -- benchmark/microbench.js
```

Microbench can be found in quicks-ng repo and needs some slight adjustments for LLRT.

**Comment by ahaoboy** [comment]
> Hi @ahaoboy! We had this before and it's a good suggestion but running the release flow is not the way to do it as it causes significant increase in PR checks.

This pr only uploads artifacts, no benchmark, but it will indeed run one more action

**Review by richarddavison — COMMENTED** [review]
If finding it hard to see a reason why artifacts should be valuable in PR pipeline?

**Comment by ahaoboy** [comment]
> If finding it hard to see a reason why artifacts should be valuable in PR pipeline?

The release cycle is very long, developers who want to use the latest version can only compile it themselves, it is easier to download it directly

**Comment by richarddavison** [comment]
> The release cycle is very long, developers who want to use the latest version can only compile it themselves, it is easier to download it directly

Right, but this seems like an X/Y problem. We should rather shorten the release cycle instead of adding CI artifacts for PRs :) However, we can add nightly versions. But then we should only upload artifacts from main `branch` and not every PR and suffix them with `-nighty` version or similar.

**Comment by ahaoboy** [comment]
> we can add nightly versions. But then we should only upload artifacts from main `branch` and not every PR and suffix them with `-nighty` version or similar.

Agreed, compiling aarch64-unknown-linux-musl on windows is very difficult, it would be great if there were nightly builds

**Comment by ahaoboy** [comment]
> Feel free to change this PR to apply this proposal or open up a new one!


I will try to add it in my fork branch, and if it works, I will open new PR

**Pull request closed without merging**
