### PR TITLE
Release GH Action

### PR DESCRIPTION
**Pull request by Sytten**
### Description of changes

- Preliminary GH action for publishing to crates.io, someone from your side need to create an account and an api token. 
- I made sure the Cargo.toml of each package is ready to publish (check if you are OK with the license)
- Added a README for the modules since the usage is different

There is no easy way to test those actions sadly...

### Checklist

- [x] Created unit tests in `tests/unit` and/or in Rust for my feature if needed
- [x] Ran `make fix` to format JS and apply Clippy auto fixes
- [x] Made sure my code didn't add any additional warnings: `make check`
- [x] Updated documentation if needed ([API.md](API.md)/[README.md](README.md)/Other)

_By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice._

### CODE REVIEW

**Comment by Sytten** [comment]
@richarddavison Anything you want to see here before we can merge it?

**Comment by bnusunny** [comment]
Could you also add `README.md` for llrt_utils mdoule?

**Comment by bnusunny** [comment]
And we need to setup an account on crates.io to publish crates. I will waite for @richarddavison to get that setup.

**Comment by Sytten** [comment]
Yup for sure!

**Review by richarddavison — APPROVED** [review]

**Pull request merged**
